// Generated by pnpm generate:metadata after rebuilding WASM. Do not edit.
import type { Language, LanguageLearningMetadata } from "../../../yap-frontend-rs/pkg";

export const LANGUAGE_LEARNING_METADATA = {
  "English": {
    "isoCode": "eng",
    "iso6391": "en",
    "status": "stable"
  },
  "French": {
    "isoCode": "fra",
    "iso6391": "fr",
    "status": "stable"
  },
  "Spanish": {
    "isoCode": "spa",
    "iso6391": "es",
    "status": "stable"
  },
  "German": {
    "isoCode": "deu",
    "iso6391": "de",
    "status": "stable"
  },
  "Italian": {
    "isoCode": "ita",
    "iso6391": "it",
    "status": "beta"
  },
  "Portuguese": {
    "isoCode": "por",
    "iso6391": "pt",
    "status": "beta"
  },
  "Russian": {
    "isoCode": "rus",
    "iso6391": "ru",
    "status": "alpha"
  },
  "Korean": {
    "isoCode": "kor",
    "iso6391": "ko",
    "status": "alpha"
  },
  "Japanese": {
    "isoCode": "jpn",
    "iso6391": "ja",
    "status": "alpha"
  },
  "ChineseSimplified": {
    "isoCode": "zho-hans",
    "iso6391": "zh",
    "status": "alpha"
  },
  "ChineseTraditional": {
    "isoCode": "zho-hant",
    "iso6391": "zh",
    "status": "alpha"
  },
  "Hindi": {
    "isoCode": "hin",
    "iso6391": "hi",
    "status": "alpha"
  },
  "Thai": {
    "isoCode": "tha",
    "iso6391": "th",
    "status": "alpha"
  }
} as const satisfies Record<Language, LanguageLearningMetadata>;
