[package]
name = "omnigram"
version = "0.1.0"
edition = "2024"

[dependencies]
language-utils = { path = "../../language-utils" }
serde.workspace = true
tokenizers = { version = "0.21", default-features = false, features = ["unstable_wasm"] }
rustc-hash = "2.0"
log.workspace = true
lasso.workspace = true
rayon = "1.10"
