name: Deploy to Fly.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'yap-ai-backend/**'
      - 'language-utils/**'
      - 'generate-data/**'
      - 'out/**/*.rkyv'
      - 'out/**/*.hash'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: big-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Pull LFS rkyv files for ai-backend
        run: git lfs pull --include="out/*_for_*/language_data.rkyv"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Auth to Fly registry
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: yap-ai-backend/Dockerfile
          push: true
          tags: registry.fly.io/yap-ai-backend:${{ github.sha }}
          cache-from: type=registry,ref=registry.fly.io/yap-ai-backend:cache
          cache-to: type=registry,ref=registry.fly.io/yap-ai-backend:cache,mode=max

      - name: Deploy to Fly.io
        run: flyctl deploy --image registry.fly.io/yap-ai-backend:${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SECRET }}